import {execFile} from 'node:child_process';
import {createServer} from 'node:http';
import {existsSync,readFileSync} from 'node:fs';
import {mkdtemp,readFile,readdir,rm,stat} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {promisify} from 'node:util';

const execFileAsync=promisify(execFile);
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const envFile=path.join(root,'.env.local');
if(existsSync(envFile))for(const raw of readFileSync(envFile,'utf8').split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#')||!line.includes('='))continue;const i=line.indexOf('=');const key=line.slice(0,i).trim();let value=line.slice(i+1).trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);if(!process.env[key])process.env[key]=value}
const ytDlp=process.env.YT_DLP_PATH||path.join(root,'tools','yt-dlp.exe');
const ffmpeg=process.env.FFMPEG_PATH||path.join(root,'node_modules','ffmpeg-static',process.platform==='win32'?'ffmpeg.exe':'ffmpeg');
const cookieBrowser=/^(edge|chrome|firefox|brave|opera|vivaldi)$/i.test(process.env.YTDLP_COOKIES_FROM_BROWSER||'')?process.env.YTDLP_COOKIES_FROM_BROWSER.toLowerCase():'';
const cookieArgs=cookieBrowser?['--cookies-from-browser',cookieBrowser]:['--no-cookies'];
const jobs=new Map();const queue=[];let active=0;
function directUrl(value){if(typeof value!=='string')return false;try{const url=new URL(value);const host=url.hostname.replace(/^www\./,'');if(['vt.tiktok.com','vm.tiktok.com'].includes(host))return url.pathname.length>1;if(host==='tiktok.com')return /\/@[^/]+\/video\/\d+/.test(url.pathname)||/^\/t\//.test(url.pathname);if(host==='instagram.com'){const match=url.pathname.match(/^\/(?:reel|reels|p)\/([A-Za-z0-9_-]{5,})\/?$/);return Boolean(match&&!['indisponivel','indisponível','unknown','undefined','null','example'].includes(match[1].toLowerCase()))}return false}catch{return false}}
function update(job,phase,progress){job.status='running';job.phase=phase;job.progress=progress}
function drain(){while(active<2&&queue.length){const task=queue.shift();active++;void task().finally(()=>{active--;drain()})}}
function enqueue(task){queue.push(task);drain()}
async function inspect(url){try{const {stdout}=await execFileAsync(ytDlp,['--dump-single-json','--skip-download','--no-playlist','--no-warnings',...cookieArgs,'--no-cache-dir','--socket-timeout','12','--retries','1','--',url],{timeout:35_000,maxBuffer:3*1024*1024,windowsHide:true});const d=JSON.parse(stdout);return{title:typeof d.title==='string'?d.title:undefined,creator:typeof d.uploader==='string'?d.uploader:typeof d.creator==='string'?d.creator:undefined,duration:typeof d.duration==='number'?d.duration:undefined,viewCount:typeof d.view_count==='number'?d.view_count:undefined,likeCount:typeof d.like_count==='number'?d.like_count:undefined,commentCount:typeof d.comment_count==='number'?d.comment_count:undefined,uploadDate:typeof d.upload_date==='string'?d.upload_date:undefined}}catch{throw new Error(`A plataforma não liberou este vídeo para análise${cookieBrowser?' usando a sessão do navegador':' sem autenticação'}.`) }}
const schema={type:'object',additionalProperties:false,properties:{summary:{type:'string'},visualHook:{type:'string'},spokenHook:{type:'string'},onScreenText:{type:'array',items:{type:'string'}},editing:{type:'string'},structure:{type:'array',items:{type:'object',additionalProperties:false,properties:{moment:{type:'string'},action:{type:'string'}},required:['moment','action']}},whyItWorks:{type:'string'},brandFit:{type:'string'},originalConcept:{type:'string'},difficulty:{type:'string',enum:['Fácil','Médio','Difícil']},evidence:{type:'array',items:{type:'string'}}},required:['summary','visualHook','spokenHook','onScreenText','editing','structure','whyItWorks','brandFit','originalConcept','difficulty','evidence']};
async function analyze(job,url,brand,title){
  if(!process.env.OPENAI_API_KEY)throw new Error('A chave da OpenAI não está configurada.');
  if(!existsSync(ytDlp)||!existsSync(ffmpeg))throw new Error('Os processadores locais de vídeo não estão disponíveis.');
  const temp=await mkdtemp(path.join(os.tmpdir(),'trend-video-'));
  try{
    update(job,'Confirmando duração e origem',8);const metadata=await inspect(url);if(metadata.duration>180)throw new Error('O vídeo ultrapassa o limite de 3 minutos.');
    update(job,'Baixando vídeo público',20);await execFileAsync(ytDlp,['--no-playlist','--no-warnings',...cookieArgs,'--no-cache-dir','--socket-timeout','15','--retries','1','--max-filesize','80M','--ffmpeg-location',path.dirname(ffmpeg),'-f','best[height<=1080]/best','--merge-output-format','mp4','-o',path.join(temp,'source.%(ext)s'),'--',url],{timeout:90_000,maxBuffer:3*1024*1024,windowsHide:true});
    const mediaName=(await readdir(temp)).find(name=>/^source\./.test(name));if(!mediaName)throw new Error('A plataforma não liberou o arquivo de vídeo.');const media=path.join(temp,mediaName);if((await stat(media)).size>85*1024*1024)throw new Error('O arquivo ultrapassa o limite de segurança.');
    update(job,'Separando áudio e cenas',38);const audio=path.join(temp,'audio.mp3');await execFileAsync(ffmpeg,['-hide_banner','-loglevel','error','-y','-i',media,'-vn','-ac','1','-ar','16000','-b:a','64k',audio],{timeout:60_000,maxBuffer:1024*1024,windowsHide:true});await execFileAsync(ffmpeg,['-hide_banner','-loglevel','error','-y','-i',media,'-vf','fps=1/4,scale=768:-2','-frames:v','30',path.join(temp,'frame-%03d.jpg')],{timeout:60_000,maxBuffer:1024*1024,windowsHide:true});
    update(job,'Transcrevendo a fala',56);const form=new FormData();form.append('model','gpt-4o-mini-transcribe');form.append('file',new Blob([await readFile(audio)],{type:'audio/mpeg'}),'audio.mp3');form.append('response_format','json');const tr=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:form});const td=await tr.json();if(!tr.ok)throw new Error(td.error?.message||'Falha ao transcrever o áudio.');
    update(job,'Analisando imagem, edição e estrutura',74);const names=(await readdir(temp)).filter(name=>/^frame-\d+\.jpg$/.test(name)).sort();if(!names.length)throw new Error('Não foi possível extrair cenas do vídeo.');const images=await Promise.all(names.map(async name=>({type:'input_image',image_url:`data:image/jpeg;base64,${(await readFile(path.join(temp,name))).toString('base64')}`,detail:'low'})));
    const prompt=`Analise rigorosamente este vídeo curto para a marca ${brand}. Referência: ${title||metadata.title||'vídeo público'}. Transcrição: ${td.text||'[sem fala reconhecível]'}. Os quadros estão em ordem cronológica a cada 4 segundos. Distinga observação de inferência. Identifique ganchos, textos legíveis, edição, estrutura, motivo de desempenho e proponha adaptação ORIGINAL sem copiar. Responda em português do Brasil.`;
    const vr=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.4-mini',input:[{role:'user',content:[{type:'input_text',text:prompt},...images]}],text:{format:{type:'json_schema',name:'video_analysis',strict:true,schema}},store:false})});const raw=await vr.text();let vd;try{vd=JSON.parse(raw)}catch{throw new Error('A análise visual retornou uma resposta inválida.')}if(!vr.ok)throw new Error(vd.error?.message||'Falha na análise visual.');const output=vd.output_text||vd.output?.flatMap(item=>item.content||[]).find(part=>part.type==='output_text')?.text;if(!output)throw new Error('A análise visual não retornou conteúdo.');job.result=JSON.parse(output);job.status='complete';job.phase='Análise audiovisual concluída';job.progress=100;
  }finally{if(temp.startsWith(os.tmpdir()))await rm(temp,{recursive:true,force:true})}
}
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'http://localhost:3000','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data))}
async function parseBody(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>65536)throw new Error('Solicitação muito grande.')}return JSON.parse(text||'{}')}
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:4317');if(req.method==='OPTIONS')return send(res,204,{});if(req.method==='GET'&&url.pathname==='/health')return send(res,200,{ok:true});if(req.method==='POST'&&url.pathname==='/inspect'){const input=await parseBody(req);if(!directUrl(input.url))return send(res,400,{error:'URL inválida.'});return send(res,200,await inspect(input.url))}if(req.method==='POST'&&url.pathname==='/analyze'){const input=await parseBody(req);if(!directUrl(input.url))return send(res,400,{error:'Use um link direto do TikTok ou Instagram.'});const id=crypto.randomUUID();const job={id,status:'queued',phase:'Na fila para análise',progress:2,createdAt:Date.now()};jobs.set(id,job);enqueue(async()=>{try{await analyze(job,input.url,input.brand||'Economize.vc',input.title||'')}catch(error){job.status='error';job.phase='Não foi possível analisar';job.error=error instanceof Error?error.message:'Falha inesperada.'}});return send(res,202,{jobId:id})}if(req.method==='GET'&&url.pathname==='/analyze'){const job=jobs.get(url.searchParams.get('id'));return job?send(res,200,job):send(res,404,{error:'Análise não encontrada.'})}return send(res,404,{error:'Rota não encontrada.'})}catch(error){return send(res,500,{error:error instanceof Error?error.message:'Falha inesperada.'})}});
server.listen(4317,'127.0.0.1',()=>console.log(`Processador de vídeo pronto em http://127.0.0.1:4317 (${cookieBrowser?`cookies: ${cookieBrowser}`:'sem cookies'})`));
